builds:
  -
    main: ./cmd/engine/main.go
    env:
    - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
before:
  hooks:
    - ./build_board.sh
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
  files:
    - board/**/*
    - public/**/*
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: battlesnakeio
    name: engine
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
